### ISSUE TITLE
Error with ResourceDictionary 

### ISSUE THREAD

**Issue by au176** [obfuscar/obfuscar#172]
Hi all.
When I add a new XAML file with ResourceDictionary to a WPF project, I get an error : " ... packages\Obfuscar.2.2.15\build\..\tools\obfuscar.console.exe " obfuscar.xml " with code -1073741819

**Comment by lextm** [comment]
Due to the changes in ILSpy, the XAML parser cannot parse many XAML/BAML elements correctly.

There is no fix at this moment, and we expect Microsoft to open source its own XAML/BAML parser soon (as part of .NET Core 3.0). This project will switch to Microsoft's implementation and then such issues should go away.

**Comment by au176** [comment]
Ок. 
Thankyou.

**Comment by lextm** [comment]
Shipped 2.2.16 with XAML/BAML support disabled completely.

**Comment by lextm** [comment]
Shipped 2.2.17 with another BAML implementation to fix the issue completely.

**Comment by lextm** [comment]
Related to #551
