### ISSUE TITLE
Self contained app

### ISSUE THREAD

**Issue by xidod** [obfuscar/obfuscar#275]
Hello, is possible to use obfuscar with self contained appplication?

**Comment by maxoptimus** [comment]
yes it should be possible because  self contained appplication in real world is only custom ms archive that contains all needed dlls;
it unpack tham somewhere in user temp folder with .net name and app title (check it when start app);
so if you config abfuscar to overrwrite correctly dll or exe inside win64 or other publish dir before vs start compresing it will work;

**Comment by maxoptimus** [comment]
is there exists better fre eobfiscator because ahen try simple net core and small and big config.xml obfuscation is go only through my code but other system assamblies and call is not obfuscated; strings is readable etc

**Comment by wegylexy** [comment]
No, it is impossible to obfuscate invocation of external assemblies, just like you can easily see all the system calls and string data in a native program.
.NET 6 self-contained apps are no longer extracts into a temp folder at runtime. Obfuscating after `PostBuildEvent` doesn't work for me.

**Comment by wegylexy** [comment]
I wonder if `Obfuscar.xml` can take `$(Configuraion)`, `$(TargetFramework)`, `$(RuntimeIdentifier)`, etc.
