### ISSUE TITLE
Obfuscating a Xamarin Forms app targetting macOS on Visual Studio for Mac

### ISSUE THREAD

**Issue by theescapers** [obfuscar/obfuscar#337]
I have successfully used obfuscar to obfuscate the Android and Windows version of my app, but cannot get it to work properly for the Mac version.

I'm using Visual Studio for Mac, and this is the obfuscar config file... (Although tried many variants)

 ```
<Obfuscator>
  <Var name="InPath" value="./Obfuscator_Input" />
  <Var name="OutPath" value="./Obfuscator_Output" />
  <Var name="HidePrivateApi" value="true" />

   <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="false" />
  <Var name="RenameFields" value="false" />
  <Var name="UseKoreanNames" value="false" />
  <Var name="HideStrings" value="false" />
  <Var name="SuppressIldasm" value="false" />
  <Var name="OptimizeMethods" value="false" />

  <Module file="$(InPath)/AppCore.dll" />


</Obfuscator>
```

Obfuscar runs with no error, but the resulting app won't run, failing with this error...

`Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

By opening before and after versions of the DLL, I can see obfuscar has added references to netstandard.

Any help is very much appreciated.

**Comment by NicolyLuisaG** [comment]
It appears that the issue you're facing is related to the addition of references to netstandard by Obfuscar in your obfuscated assembly. This is causing a runtime error because the referenced netstandard version is not being resolved correctly.

The error message indicates that the assembly 'netstandard' with version 2.0.0.0 cannot be found. This suggests that there might be a version mismatch between the netstandard version that your obfuscated assembly references and the one that's available in your environment.

Here are a few steps you can try to address this issue:

Check Obfuscar Version: Ensure that you're using a version of Obfuscar that is compatible with the version of .NET or .NET Standard you're targeting in your project.
Check Dependencies: Look into the dependencies of your project and ensure that there are no version conflicts or missing dependencies that might be causing this issue.
Upgrade Obfuscar: If you're not already using the latest version of Obfuscar, consider upgrading to see if the issue has been addressed in newer releases.
Configuration: Review your Obfuscar configuration settings to see if there are any settings related to assembly references or dependency handling that you can adjust.
Investigate Assembly Binding: Investigate the assembly binding in your project. It's possible that the obfuscated assembly is referencing a specific version of netstandard that is not compatible with your environment. You might need to adjust your project's assembly binding redirects to resolve this.
Test Different Configurations: Try experimenting with different Obfuscar configuration settings to see if any specific setting is causing the issue. For example, you could try disabling specific features one at a time to isolate the problem.
Check Obfuscated DLL Content: Open the obfuscated DLL in a tool like ILSpy to inspect its content and see if there are any unusual references to netstandard.
If the problem persists after trying these steps, it might be helpful to seek assistance on forums or communities related to Obfuscar or .NET development.

**Comment by lextm** [comment]
Since Xamarin Forms is deprecated, such issues are closed now.
