### ISSUE TITLE
Obfuscating idea/suggestion

### ISSUE THREAD

**Issue by lk-davidegironi** [obfuscar/obfuscar#412]
I'm looking at obfuscator to obfuscate a library which contains a little bit of math my company and I have worked on for weeks. Obfuscar does a great job on that, I've made a private method called by a public method on the library, the private is obfuscated, but the constant we use and the math functions (Math.Sqrt... and so on) still is visible. I'm wondering if there's a way to obfuscate that. My idea is to embed this math in a string, then use CSharpScript to evaluate that. What do you thing? Thanks!

**Comment by lextm** [comment]
Hidden strings are reversible so that's not going to help at all.

Any call to BCL is desired to be visible, because without that there is no way to consume such API.

If you really want to protect an algorithm, the only way is to make it a SaaS solution hosted in a private cloud. The moment you deployed the algorithm to a client machine as a library, native or managed, you should assume that an intermediate level programmer can decompile and reverse engineer most if not all of your code.

Obfuscate won't help much, so are many of the commercial obfuscation tools.

**Comment by lk-davidegironi** [comment]
Thanks lextm. I know, indeed anything deploy has to be executed, so in some way disassembled by the machine or a malicious user. It was just to make them life harder. I should think about an API service maybe for this algorithm. Thanks again even for this good project.
