### ISSUE TITLE
Obfusced DLL resolve in an error

### ISSUE THREAD

**Issue by zonetecde** [obfuscar/obfuscar#420]
I tried to obfuscate my WPF c# software, with this XML file : 

`<?xml version='1.0'?>
<Obfuscator>
	<Var name="InPath" value=".\bin\Debug\net6.0-windows" />
	<Var name="OutPath" value=".\bin\Debug\Obfuscator_Output" />

	<AssemblySearchPath path=".\bin\Debug\net6.0-windows" />
	<AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.16\ref\net6.0"/>

	<Module file="$(InPath)\Traqueur TUI Fly.dll" />
	<Module file="$(InPath)\GU.dll" />
	<Module file="$(InPath)\Classes.dll" />

	<Var name="KeepPublicApi" value="false" />
	<Var name="HidePrivateApi" value="true" />
</Obfuscator>`

It generates me the dll, then when I replace the old dll with the new generated one, my software crash with this error:

![image](https://user-images.githubusercontent.com/56195432/233864292-adbff640-9b5f-451d-b13f-4cd223d95a2d.png)

Is there anything I can do to make it works?

note: it works if I enable "KeepPublicApi" and disable "HidePrivateApi".

**Comment by lextm** [comment]
Like [many of the closed issues in this area](https://github.com/obfuscar/obfuscar/issues?q=label%3Aarea%3AWPF%2FUWP+is%3Aclosed), you will have to exclude many classes/methods from obfuscation yourself in order to make the obfuscated application work as expected.

This is due to the nature of obfuscation itself and the design of WPF. There isn't a simple way for a free obfuscator to fully support that.

**Comment by lextm** [comment]
Duplicate to #551
