### ISSUE TITLE
Bad obfuscator or just not done yet?

### ISSUE THREAD

**Issue by DosX-dev** [obfuscar/obfuscar#438]
Obfuscar is by far the worst on Github for code protection, but I'm sure that it has prospects for development.

Simple renaming can hardly be called "code obfuscation" since it is easily removed by de4dot along with string encryption. Therefore, I am interested in the answer to the question - will code mutations be added (control flow obfuscation, virtualization, resource encryption etc)

You can consider modifications to ConfuserEx or MindLated and do something similar.

In the meantime, it makes no sense to use Obfuscar, since the project is either too young and underdeveloped, or there is too little work on it.

**Comment by lextm** [comment]
Thanks for the comments, but I don't think they make any sense.

* “since it is easily removed by de4dot” isn't true. Meanings in names are lost forever in obfuscation, so de4dot won't be able to reverse it. That's enough for a free tool like Obfuscar, as it raises the bar of reverse engineering a little bit.
* String encryption (or many other cool obfuscation features) is reversible and that's common knowledge. Since you mentioned de4dot, I wonder why you still want "virtualization, resource encryption" as de4dot can reverse them easily.
* If you love other tools like ConfuserEx so much, why not spend your time there? Every project has its own goals, and clearly Obfuscar aims on a very small scope.
