### ISSUE TITLE
.Net7 ReflectionTypeLoadException: Unable to load one or more of the requested types. 

### ISSUE THREAD

**Issue by michalciolek** [obfuscar/obfuscar#445]
Obfuscar unnecessarily renames methods that are implemention of some external interface. I get an exception:

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'GetObjectData' in type 'A.e' from assembly 'X, Version=2.10.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

For example, I have `TestSerializable` which implements [ISerializable](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable?view=net-7.0) from `System.Runtime.dll`

```
namespace Test
{
    public class TestSerializable : ISerializable
    {
        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {

        }
    }
}
```

After obfuscation (without any error) I get:

1) for .NET 7 (assembly `X.dll`)
```
[X]Test.TestSerializable -> [X]A.e
{
	[X]Test.TestSerializable::GetObjectData[2]( [System.Runtime]System.Runtime.Serialization.SerializationInfo, [System.Runtime]System.Runtime.Serialization.StreamingContext ) -> A

	[X]Test.TestSerializable::.ctor[0]( ) skipped:  special name
}
```
`GetObjectData` method should be skipped but is renamed to `A`!	

2) for .Net Framework (assembly `X.exe`)
```
[X]Test.TestSerializable -> [X]A.e
{

	[X]Test.TestSerializable::GetObjectData[2]( [mscorlib]System.Runtime.Serialization.SerializationInfo, [mscorlib]System.Runtime.Serialization.StreamingContext ) skipped:  external base class or interface
	[X]Test.TestSerializable::.ctor[0]( ) skipped:  special name
}
```
Renaming `GetObjectData` was skipped, OK.
	
To fix this I have added `System.Runtime.dll` path to AssemblySearchPath:

```
<AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.12\ref\net7.0\" />
```

**Comment by deerchao** [comment]
This is happending for me too. 
Worked around this by chaging the class to public.

**Comment by ALiwoto** [comment]
Hi, this also used to happen to one of our codebases as well, I believe the reasons are:

1. You have an internal (or private) class which inherits from a public class.
2. That class has some abstract method which **has** to be overridden by any class that inherits it.
3. After obfuscation, methods names and properties names of your child class are going to be renamed, which means it will no longer override the parent's class abstract methods/properties.

One of the workaround for this, is indeed making your child class a _public_ class, so its public properties/methods don't get renamed.
Another solution is to make the obfuscators more smart (because I tried this with other .NET obfuscators as well, got the same results), in a way that they ignore overridden properties/methods.

I believe you can also use [[System.Reflection.ObfuscationAttribute()]](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.obfuscationattribute?view=net-8.0) attribute on your method and set its [Exclude](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.obfuscationattribute.exclude?view=net-8.0#system-reflection-obfuscationattribute-exclude) parameter to true, so it doesn't get obfuscated anymore (tho it's entirely up to the obfuscation tool used to respect this or not).

**Comment by lextm** [comment]
We have the test case in `FunctionOverridingTests` that covers typical `ISerializable` scenarios. But this report seems to point to a very special setup, which we don't have time to investigate further. Luckily, the workaround is straightforward.

Pull requests are welcome if anyone figures out the cause.
