### ISSUE TITLE
In asynchronous methods,SkipStringHiding does not work

### ISSUE THREAD

**Issue by deakintsang** [obfuscar/obfuscar#481]
Hello,
In the asynchronous method, I want to skip strings.

```
 <Module file="$(InPath)\WpfApp9.dll" >
   <SkipStringHiding type="WpfApp9.Utils" name="HttpPost" />
   <SkipStringHiding type="WpfApp9.Utils" name="Dtest2" />
   <SkipStringHiding type="WpfApp9.Utils" name="Dtest3" />
   <SkipStringHiding type="WpfApp9.Utils" name="Dtest5" />
 </Module>
```

```

        public void Dtest()
        {
            string fff = "fsdfsdfd";
        }

        public Task<string> Dtest2()
        {
            string fff = "fsdfsdfd";
            return null;
        }
        
        public async void Dtest3()
        {
            string fff = "fsdfsdfd";
            //return null;
        }

        public void Dtest5()
        {
            string fff = "fsdfsdfd";
            //return null;
        }


```
![image](https://github.com/user-attachments/assets/db5d5b67-27e9-438a-b992-31689c12ecc2)

Thank you for your time and consideration. I appreciate any feedback you can provide.
Best regards！

**Comment by lextm** [comment]
In short, Obfuscar does execute what the settings asked, by scanning the strings inside `Dtest3` method in the assembly and don't hide any of them.

The reason why you see that string remains hidden is because that C# compiler moved this string to a private nested class which is used to support the `async void` pattern (private implementation details of the state machines).

Since `<SkipStringHiding type="WpfApp9.Utils" name="Dtest3" />` does not apply to that private class, the string was converted to hidden by Obfuscar.

If you are the developer of such programs, please try to extract the contents of Dtest3 to a pure async method, for example

``` csharp
public async void Dtest3()
{
    await DtestN();
}

public async Task DtestN()
{
    string fff = "fsdfsdfd";
    //return null;
}
```
so that you can fully control the string processing in `DtestN` instead.

Currently there is no plan to improve Obfuscar to detect the state machine classes as that's bit of complicated.
